queue commands
tenantcloud/tcctl pull request #24
Opened 2020-09-10 16:53 UTC by odebretseni

2020-09-11 09:13 UTC, BrunIF requested changes

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/finish_all_queues
> +      fi
можна писати комент, щоб було зрозуміло де сталася проблема 
через `_message` error
Тоді не треба буде робити вихід окремо. І буде повідомлення про помилку

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/finish_all_queues
> +  fi
те саме 
`[[ "$_error_code" -gt "0" ]] && _message "Error on queue statte terminate when empty" "error" "128"`

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/finish_all_queues
> +if [ -z "$PARALLEL_PROCESS" ]; then
краще зробити так. Якщо нічого не вказано, то тут брати дефолтне значенна. Наприклад, 8 потоків.

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/finish_all_queues
> +  _message "$__MSG" "error" "$_error_code"
тут можна робити однією командою, якщо повідомлення не велике.
Також треба писати не машинні повідомлення, а людською мовою. 
```bash
_message "Error ending all queues" "error" "$_error_code"
```

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/finish_all_queues.help
> +tcctl laravel deployment finish_all_queues --parallel-process 8 --queue high,default,export,reports,promo,low,notification,convert-to-pdf,cron,deploy
я не просто так давав лапки. Якщо дадуть пробіл, то ти вже щось можеш втратити
`--queue "high,default,export,reports, promo,low, notification,convert-to-pdf,cron,deploy"`

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/finish_all_queues.help
> +tcctl laravel deployment finish_all_queues --parallel-process 8 --queue high,default,export,reports,promo,low,notification,convert-to-pdf,cron,deploy
Бажано всі значення завжди закривати в лапки `"` чи `'`

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/queue_work
> +    done
якщо буде дві черги, до прикладу, `low`, `high` то ти запустиш 16 процесів. Може не стянути сервер.
Треба було просто додати у лапки ці змінні до аргументу `--queue="low,high"`

2020-09-11 09:13 UTC, BrunIF commented on tc/app/laravel/deployment/create_symlink
> +  __destination=$2
```
  __source="$1"
  __destination="$2"
```
вже у одному стилі це робити.

2020-09-11 13:36 UTC, odebretseni commented on tc/app/laravel/deployment/finish_all_queues
> +  _message "$__MSG" "error" "$_error_code"
тут помилка не черг а відсутності ключів - тут ніби і мало б так бути

2020-09-11 13:54 UTC, odebretseni commented on tc/app/laravel/deployment/finish_all_queues
> +if [ -z "$PARALLEL_PROCESS" ]; then
PARALLEL_PROCESS="8"
на початку я це вказую

2020-09-14 13:47 UTC, BrunIF approved these changes

2020-09-15 08:17 UTC, vikfedkiv approved these changes

2020-09-15 15:24 UTC, merged