config: Add laravel cache clear command
tenantcloud/tcctl pull request #25
Opened 2020-09-11 09:43 UTC by vikfedkiv

2020-09-11 09:57 UTC, BrunIF requested changes

2020-09-11 09:57 UTC, BrunIF commented on tc/app/laravel/cache/clear
> +  fi
Перероби на case. Код буде меншим і читабельнішим.

2020-09-14 13:51 UTC, BrunIF approved these changes

2020-09-14 13:54 UTC, BrunIF commented
Я б казав переробити код, бо там дуже громісткий код. Там можна просто ловити коди кожної команди і перевіряти коди. 
Та й є дублювання. Краще то зробити функцією або якось грамотніше.

2020-09-15 06:41 UTC, vikfedkiv commented
> Я б казав переробити код, бо там дуже громісткий код. Там можна просто ловити коди кожної команди і перевіряти коди.
> Та й є дублювання. Краще то зробити функцією або якось грамотніше.

Done.

2020-09-15 07:48 UTC, BrunIF requested changes

2020-09-15 07:48 UTC, BrunIF commented on tc/app/laravel/cache/clear
> +function check_exit_code {
назва функції не правильна. 
Воно виконує команду з перевіркою. А тут наголос на помилку виходу. 
`run_programm_with_error_check` 
Якось в цьому стилі.

2020-09-15 08:08 UTC, BrunIF approved these changes

2020-09-15 09:35 UTC, odebretseni approved these changes

2020-09-15 15:19 UTC, merged