refactoring
tenantcloud/tcctl pull request #28
Opened 2020-09-18 14:49 UTC by odebretseni

2020-09-21 07:05 UTC, BrunIF requested changes

2020-09-21 07:05 UTC, BrunIF commented on tc/app/aws/wait_replicas_zero_lag
> +  __MSG="Command: tcctl aws wait_replicas_zero_lag missed --slack-channel"
У нас є дефолтний канал, якщо він не вказаний. То ж можна перевизначати тільки при потребі.

2020-09-21 16:13 UTC, odebretseni commented on tc/app/aws/wait_replicas_zero_lag
> +      slack chat send "We were unable to find replica's DB instances and STOP deployment process on $(hostname)" "${__slack_channel}" > /dev/null
так домовились не використовувати команди tcctl всерединsі команд tcctl

2020-09-21 16:17 UTC, odebretseni commented on tc/app/aws/wait_replicas_zero_lag
> +  __MSG="Command: tcctl aws wait_replicas_zero_lag missed --slack-channel"
так є потреба - в staging скрипті - це #staging-updates, в production - #production-updates

2020-09-22 06:40 UTC, BrunIF commented on tc/app/aws/wait_replicas_zero_lag
> +  __MSG="Command: tcctl aws wait_replicas_zero_lag missed --slack-channel"
я до того, що робити обов'язковим цей параметр не потрібно. Ти будеш й так задавати канал.

2020-09-22 06:41 UTC, BrunIF commented on tc/app/aws/wait_replicas_zero_lag
> +      slack chat send "We were unable to find replica's DB instances and STOP deployment process on $(hostname)" "${__slack_channel}" > /dev/null
сорсиш його функцію і запускаєш. Не використовуючи зовнішні команди.

2020-09-22 06:53 UTC, odebretseni commented on tc/app/aws/wait_replicas_zero_lag
> +      slack chat send "We were unable to find replica's DB instances and STOP deployment process on $(hostname)" "${__slack_channel}" > /dev/null
так нема функцій окремих для надсилання, є команда і якщо я створю окрему функцію для цього то це дублювання коду виходить або я не розумію що мається на увазі...

2020-09-22 08:14 UTC, odebretseni commented on tc/app/aws/wait_replicas_zero_lag
> +  __MSG="Command: tcctl aws wait_replicas_zero_lag missed --slack-channel"
а якій вказувати дефолтний канал?

2020-09-22 08:21 UTC, vikfedkiv commented on tc/app/aws/wait_replicas_zero_lag
> +  __MSG="Command: tcctl aws wait_replicas_zero_lag missed --slack-channel"
#devops-notifications всюди ставимо

2020-09-22 18:57 UTC, BrunIF requested changes

2020-09-22 18:57 UTC, BrunIF commented on tc/app/aws/wait_replicas_zero_lag
> +SLACK_CHANNEL="#devops-notifications"
цю змінну треба запхати сюда `$CLI_DIR/tc/app/slack/functions` щоб постійно не оголошувати. А тут забрати. 

Тобто якщо порожнє `"$2"` то `__slack_channel="#devops-notifications"` у функції `slack_send_message`

2020-09-22 18:57 UTC, BrunIF commented on tc/app/aws/wait_replicas_zero_lag
> +      slack_send_message "We were unable to find replica's DB instances and STOP deployment process on $(hostname)" "${__slack_channel}"
якщо буде дефолтний канал, то можна буде не оголошувати його окремо, а тільки перевизначати при необхідності.

2020-09-22 19:11 UTC, odebretseni commented on tc/app/aws/wait_replicas_zero_lag
> +      slack_send_message "We were unable to find replica's DB instances and STOP deployment process on $(hostname)" "${__slack_channel}"
я її тут оголошую тіки заради шелчека...
https://monosnap.com/file/sCcTKNSGHb92WRb73SOInd26oM6Jcr

2020-09-23 07:37 UTC, BrunIF requested changes

2020-09-23 07:37 UTC, BrunIF commented on tc/app/aws/wait_replicas_zero_lag
> +      slack_send_message "We were unable to find replica's DB instances and STOP deployment process on $(hostname)" "${__slack_channel}"
можна в функції задісейблити цю помилку (тільки у функції.)

2020-09-23 11:35 UTC, BrunIF approved these changes

2020-09-23 12:05 UTC, vikfedkiv approved these changes

2020-09-23 13:52 UTC, merged