added tcctl helpers env update_repository_version
tenantcloud/tcctl pull request #41
Opened 2020-11-23 15:28 UTC by odebretseni

2020-11-23 15:51 UTC, BrunIF requested changes

2020-11-23 15:51 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +__output=$( git log "${__pr_commit}"..HEAD --ancestry-path --merges --oneline --color | tail -n 1 | awk '{ print $4 }' )
довжина рядка не більше 80 (пл можливості)

```bash
__output=$( git log "${__pr_commit}"..HEAD --ancestry-path --merges --oneline --color \
  | tail -n 1 \
  | awk '{ print $4 }' )
```

2020-11-23 15:51 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +echo "PR_COMMIT: $__pr_commit PR_BRANCH: $__pr_branch SOURCE_BRANCH_NAME: $__source_branch_name"
це інформація для дебагу. її можна не виводити, але якщо виводити, то через `_message`

2020-11-23 15:51 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +  echo "Current git version: $__output"
`_message`

2020-11-23 15:51 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +echo "New version: $__site_version"
`_message`

2020-11-23 15:51 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +    echo "Added new files"
`_message`
......
всюди.

2020-11-23 15:51 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +    echo "Push code to remote repository $__git_remote_url"
порозділяти через ентер логічні блоки. бо не видно, що й до чого.  Все злито. Погано читається.

2020-11-23 17:32 UTC, BrunIF requested changes

2020-11-23 17:32 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +tcctl message --text "PR_COMMIT: $__pr_commit PR_BRANCH: $__pr_branch SOURCE_BRANCH_NAME: $__source_branch_name"
може `_message`?

2020-11-23 19:05 UTC, odebretseni commented on tc/app/helpers/env/update_repository_version
> +tcctl message --text "PR_COMMIT: $__pr_commit PR_BRANCH: $__pr_branch SOURCE_BRANCH_NAME: $__source_branch_name"
так це не виклик функції а команда, ми ж домовились заміняти ехо на команду

2020-11-24 07:59 UTC, BrunIF requested changes

2020-11-24 07:59 UTC, BrunIF commented on tc/app/helpers/env/update_repository_version
> +tcctl message --text "PR_COMMIT: $__pr_commit PR_BRANCH: $__pr_branch SOURCE_BRANCH_NAME: $__source_branch_name"
???
В проектах Laravel, але ж не тут

2020-11-24 09:42 UTC, BrunIF approved these changes

2020-11-24 09:42 UTC, merged