feature : added string, docker, dns functions and command
tenantcloud/tcctl pull request #75
Opened 2021-03-16 10:07 UTC by odebretseni

2021-03-16 13:27 UTC, BrunIF requested changes

2021-03-16 13:27 UTC, BrunIF commented on tc/app/docker/container/restart
> +__cid=$(docker ps -q -f status=running -f name=^/tc-home-"$container_name")
better filter value in quotes
```
__cid=$(docker ps -q -f "status=running" -f "name=^/tc-home-$container_name")
```

2021-03-16 13:27 UTC, BrunIF commented on tc/app/docker/container/restart
> +if [ ! "${__cid}" ]; then
it's the wrong condition
You get an error if a docker daemon not started.

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/append_string_after
> +. "${$CLI_DIR/tc/app/dns/functions}"
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/delete_string
> +. "${$CLI_DIR/tc/app/dns/functions}"
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/functions
> +  __OS=$(tcctl helpers get_os)
inside tcctl command, we don't use tcctl. Only functions.

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/functions
> +}
duplicate with replace_string. Use parameters for functions.

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/functions
> +  fi
you can create function for this code. It's copy/paste.

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/insert_string
> +. "${$CLI_DIR/tc/app/dns/functions}"
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/insert_string.help
> +--file-name          "file name"  [REQUIRE]
Require:
--insert-string      "the string to insert"
--file-name          "file name" 

Optional:
--optianal_key

It's better

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/replace_string
> +. "${$CLI_DIR/tc/app/dns/functions}"
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/replace_string
> +fi
same error

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/replace_string.help
> +--file-name          "file name"  [REQUIRE]
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/replace_string_with_escapes
> +. "${$CLI_DIR/tc/app/dns/functions}"
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/replace_string_with_escapes
> +fi
change

2021-03-16 13:27 UTC, BrunIF commented on tc/app/helpers/replace_string_with_escapes.help
> +--file-name          "file name" [REQUIRE]
change

2021-03-18 07:52 UTC, BrunIF requested changes

2021-03-18 08:00 UTC, odebretseni commented on tc/app/dns/cert_gen.help
> +tcctl dns cert_gen --dns-name "FILE NAME"
this is no longer there

2021-03-18 12:04 UTC, BrunIF approved these changes

2021-03-19 10:49 UTC, BrunIF approved these changes

2021-03-19 10:50 UTC, vikfedkiv approved these changes

2021-03-19 10:52 UTC, merged